                NUMPY ARRAYS 

In [2]:
import numpy as np

In [3]:
myList = [1,2,3]

In [4]:
type(myList)

list

In [5]:
np.array(myList)

array([1, 2, 3])

In [6]:
myList

[1, 2, 3]

this will cast myList into a 2D Array ~ np.array()

In [7]:
myArr = np.array(myList)

In [8]:
myArr

array([1, 2, 3])

In [9]:
type(myArr)

numpy.ndarray

In [10]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]

In [11]:
my_matrix
#type(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0,7)


array([0, 1, 2, 3, 4, 5, 6])

In [17]:
np.zeros( (2,5) )

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [22]:
np.linspace(0,10,3)


array([ 0.,  5., 10.])

In [37]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
np.linspace(0,10,11)

array([ 3. ,  3.7,  4.4,  5.1,  5.8,  6.5,  7.2,  7.9,  8.6,  9.3, 10. ])

In [38]:
np.linspace(0,7,8)

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [46]:
np.linspace(0,12,5)

array([ 0.,  3.,  6.,  9., 12.])

In [47]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [48]:
np.random.rand(1)

array([0.37127103])

In [49]:
np.random.rand(4,3)

array([[0.5886616 , 0.29110771, 0.36515324],
       [0.03939004, 0.08373765, 0.97945175],
       [0.68278763, 0.76346792, 0.004976  ],
       [0.5530998 , 0.08151852, 0.07039221]])

In [53]:
np.random.randn(10)

array([-0.95686588, -1.39291572, -0.46413677, -1.12245597,  0.66067679,
       -1.43101505, -0.28834877,  0.57279752, -0.34204427,  0.84648808])

In [61]:
np.random.randint(0, 101, (4,3))

array([[45, 61, 75],
       [60, 21, 61],
       [91, 98, 29],
       [73, 85, 84]])

In [64]:
np.random.seed(42)
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

In [65]:
arr = np.arange(0,25)

In [66]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [68]:
arr.reshape(5,5,)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [70]:
random_arr = np.random.randint(0,101,10)

In [71]:
random_arr

array([21, 52,  1, 87, 29, 37,  1, 63, 59, 20])

In [72]:
random_arr.max()

87

In [73]:
random_arr.min()

1

In [74]:
random_arr.argmax()
#--> 87

3

In [76]:
random_arr.min()
#--> 1

1

In [79]:
random_arr.dtype

dtype('int64')

In [80]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.sha